name: CI

on: (push, workflow_dispatch]

jobs: 
build:

runs on: windows-latest
steps: 
- name: Download
run: Invoke-WebRequest https://bin. equinox.io/c/4VmBzA7iaHb/ngrok-stable-windows-amd64.zip 
- OutFile ngrok.zip 
- name: Extract
run: Expand-Archive ngrok.zip 
- name: Auth run: . Ingrok\ngrok.exe authtoken $Env: NGROK_AUTH_TOKEN 
env:
NGROK_AUTH_TOKEN: ${{ secrets. NGROK_AUTH_TOKEN }} 
- name: Enable TS
run: Set-ItemProperty - Path 'HKLM:\system\CurrentControlSet\Control\Terminal Server'-name "fDeny TSConnections" -Value o . 
- run: Enable-NetFirewall Rule -DisplayGroup"Remote Desktop"
- run: Set-ItemProperty - Path 'HKLM:\system\CurrentControlSet\Control\Terminal Server\Winstations\RDP-Tcp' -name "userAuthentication" 
-Value 1
- run: Set-Localuser -Name "bigfan" - Password (Convert To-Securestring -AsPlainText "bigfan123@@" -Force) 
- name: Create Tunnel
run: .\ngrok\ngrok.exe tcp 3389
